// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: UserMessage.capnp

#include "UserMessage.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<27> b_c9efaa4d9fa82dc0 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    192,  45, 168, 159,  77, 170, 239, 201,
     18,   0,   0,   0,   1,   0,   1,   0,
    244,  80, 213, 207, 103, 225, 119, 246,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     78,   0,   0,   0, 206,   0,   0,   0,
     21,   0,   0,   0, 242,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     85, 115, 101, 114,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  85, 115, 101, 114,  77, 101,
    115, 115,  97, 103, 101,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
    156,  99,  88,  32,  83, 216, 129, 184,
     13,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 111, 109, 109,  97, 110, 100,   0, }
};
::capnp::word const* const bp_c9efaa4d9fa82dc0 = b_c9efaa4d9fa82dc0.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_c9efaa4d9fa82dc0[] = {
  &s_b881d8532058639c,
};
static const uint16_t m_c9efaa4d9fa82dc0[] = {0};
static const uint16_t i_c9efaa4d9fa82dc0[] = {0};
const ::capnp::_::RawSchema s_c9efaa4d9fa82dc0 = {
  0xc9efaa4d9fa82dc0, b_c9efaa4d9fa82dc0.words, 27, d_c9efaa4d9fa82dc0, m_c9efaa4d9fa82dc0,
  1, 1, i_c9efaa4d9fa82dc0, nullptr, nullptr, { &s_c9efaa4d9fa82dc0, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<65> b_b881d8532058639c = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    156,  99,  88,  32,  83, 216, 129, 184,
     30,   0,   0,   0,   1,   0,   1,   0,
    192,  45, 168, 159,  77, 170, 239, 201,
      1,   0,   7,   0,   1,   0,   3,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  50,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 175,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     85, 115, 101, 114,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  85, 115, 101, 114,  77, 101,
    115, 115,  97, 103, 101,  46,  99, 111,
    109, 109,  97, 110, 100,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   4,   0,
      0,   0, 255, 255,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   3,   0,   1,   0,
     76,   0,   0,   0,   2,   0,   1,   0,
      1,   0, 254, 255,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   3,   0,   1,   0,
     80,   0,   0,   0,   2,   0,   1,   0,
      2,   0, 253, 255,   0,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     77,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     76,   0,   0,   0,   3,   0,   1,   0,
     88,   0,   0,   0,   2,   0,   1,   0,
    108, 111, 103, 111, 110,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    254, 228, 204, 232, 134,  20, 169, 186,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115, 101, 116,  78, 105,  99, 107,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    143,  53, 189,  62,  90, 219, 222, 137,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115, 101, 110, 100,  67, 104,  97, 116,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      8,  72,  11, 154, 255, 225, 226, 234,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b881d8532058639c = b_b881d8532058639c.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_b881d8532058639c[] = {
  &s_89dedb5a3ebd358f,
  &s_baa91486e8cce4fe,
  &s_c9efaa4d9fa82dc0,
  &s_eae2e1ff9a0b4808,
};
static const uint16_t m_b881d8532058639c[] = {0, 2, 1};
static const uint16_t i_b881d8532058639c[] = {0, 1, 2};
const ::capnp::_::RawSchema s_b881d8532058639c = {
  0xb881d8532058639c, b_b881d8532058639c.words, 65, d_b881d8532058639c, m_b881d8532058639c,
  4, 3, i_b881d8532058639c, nullptr, nullptr, { &s_b881d8532058639c, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<34> b_baa91486e8cce4fe = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    254, 228, 204, 232, 134,  20, 169, 186,
     18,   0,   0,   0,   1,   0,   0,   0,
    244,  80, 213, 207, 103, 225, 119, 246,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     10,   1,   0,   0,  48,   1,   0,   0,
     21,   0,   0,   0, 226,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     85, 115, 101, 114,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  85, 115, 101, 114,  76, 111,
    103, 111, 110,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    110,  97, 109, 101,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_baa91486e8cce4fe = b_baa91486e8cce4fe.words;
#if !CAPNP_LITE
static const uint16_t m_baa91486e8cce4fe[] = {0};
static const uint16_t i_baa91486e8cce4fe[] = {0};
const ::capnp::_::RawSchema s_baa91486e8cce4fe = {
  0xbaa91486e8cce4fe, b_baa91486e8cce4fe.words, 34, nullptr, m_baa91486e8cce4fe,
  0, 1, i_baa91486e8cce4fe, nullptr, nullptr, { &s_baa91486e8cce4fe, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<34> b_89dedb5a3ebd358f = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    143,  53, 189,  62,  90, 219, 222, 137,
     18,   0,   0,   0,   1,   0,   0,   0,
    244,  80, 213, 207, 103, 225, 119, 246,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    121,   1,   0,   0, 164,   1,   0,   0,
     21,   0,   0,   0, 242,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     85, 115, 101, 114,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  85, 115, 101, 114,  83, 101,
    116,  78, 105,  99, 107,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    110, 101, 119,  78,  97, 109, 101,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_89dedb5a3ebd358f = b_89dedb5a3ebd358f.words;
#if !CAPNP_LITE
static const uint16_t m_89dedb5a3ebd358f[] = {0};
static const uint16_t i_89dedb5a3ebd358f[] = {0};
const ::capnp::_::RawSchema s_89dedb5a3ebd358f = {
  0x89dedb5a3ebd358f, b_89dedb5a3ebd358f.words, 34, nullptr, m_89dedb5a3ebd358f,
  0, 1, i_89dedb5a3ebd358f, nullptr, nullptr, { &s_89dedb5a3ebd358f, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<51> b_eae2e1ff9a0b4808 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
      8,  72,  11, 154, 255, 225, 226, 234,
     18,   0,   0,   0,   1,   0,   1,   0,
    244,  80, 213, 207, 103, 225, 119, 246,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     58,   2,   0,   0, 126,   2,   0,   0,
     21,   0,   0,   0, 250,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     85, 115, 101, 114,  77, 101, 115, 115,
     97, 103, 101,  46,  99,  97, 112, 110,
    112,  58,  85, 115, 101, 114,  83, 101,
    110, 100,  67, 104,  97, 116,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     49,   0,   0,   0,  82,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     48,   0,   0,   0,   3,   0,   1,   0,
     60,   0,   0,   0,   2,   0,   1,   0,
     99, 111, 110, 116, 101, 110, 116, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 105, 109, 101, 115, 116,  97, 109,
    112,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_eae2e1ff9a0b4808 = b_eae2e1ff9a0b4808.words;
#if !CAPNP_LITE
static const uint16_t m_eae2e1ff9a0b4808[] = {0, 1};
static const uint16_t i_eae2e1ff9a0b4808[] = {0, 1};
const ::capnp::_::RawSchema s_eae2e1ff9a0b4808 = {
  0xeae2e1ff9a0b4808, b_eae2e1ff9a0b4808.words, 51, nullptr, m_eae2e1ff9a0b4808,
  0, 2, i_eae2e1ff9a0b4808, nullptr, nullptr, { &s_eae2e1ff9a0b4808, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// UserMessage
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t UserMessage::_capnpPrivate::dataWordSize;
constexpr uint16_t UserMessage::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind UserMessage::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* UserMessage::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// UserMessage::Command
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t UserMessage::Command::_capnpPrivate::dataWordSize;
constexpr uint16_t UserMessage::Command::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind UserMessage::Command::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* UserMessage::Command::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// UserLogon
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t UserLogon::_capnpPrivate::dataWordSize;
constexpr uint16_t UserLogon::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind UserLogon::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* UserLogon::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// UserSetNick
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t UserSetNick::_capnpPrivate::dataWordSize;
constexpr uint16_t UserSetNick::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind UserSetNick::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* UserSetNick::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// UserSendChat
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t UserSendChat::_capnpPrivate::dataWordSize;
constexpr uint16_t UserSendChat::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind UserSendChat::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* UserSendChat::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE



